# Generated by Django 3.1.3 on 2022-01-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question_id',
        ),
        migrations.AddField(
            model_name='choice',
            name='question_id',
            field=models.ManyToManyField(related_name='choices', to='onlinecourse.Question'),
        ),
    ]
